### PR TITLE
dev/gfdl branch remove deprecated io 

### LINKED ISSUE #256: deprecated fmsio remains in the dycore
**Describe the bug**
There is still some use of deprecated fmsio subroutines.  These need to be removed or replaced with fms2io.

**To Reproduce**
Compile SHiELD and SHiELD solo with the branch in [this FMS PR](https://github.com/NOAA-GFDL/FMS/pull/1064)
You will get compiler errors relates to subroutines that do not exist.

**Expected behavior**
SHiELD and solo should compile.

**System Environment**
Testing on gaea c4 with intel

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by laurenchilutti**
**Description**

Removing the final remaining deprecated fmsio calls within the dev/gfdl branch.

Fixes #256 

**How Has This Been Tested?**

Still needs to be fully tested - requires that all components of the GFDL models be updated.

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by laurenchilutti** [comment]
@uramirez8707 and I were discussing how and when to merge in these changes.  My concern is that this PR removes some calls to old fmsio that are needed while other components still use old io (e.g. `set_domain`, `nullify_domain`, `set_filename_appendix`).  Uriel has suggested using `#ifdef` statements surounding the calls that need to stay until old fmsio is fully deprecated.  Another option is to keep this update on a separate branch while testing (could be dev/gfdl_test) once we fully test that branch with the GFDL models, FMS 2023.02-alpha1, and all other updated components, we can then merge it into the dev/gfdl branch.

@bensonr @uramirez8707 what would you recommend I do?

**Comment by bensonr** [comment]
Besides atmospheric physics, what other things rely on FV3 for these calls?

**Comment by laurenchilutti** [comment]
I don't think there is anything else that relies on FV3 for those calls.

**Comment by laurenchilutti** [comment]
It should be safe to merge this as users should be using tags for the dev/gfdl branch.  @uramirez8707 @bensonr This PR is just a cherry-pick of the commits in my other PR which you have both reviewed.  Could you please review this as well and I will merge this?

File: driver/solo/fv_phys.F90 [hunk 1]
```diff
@@ -1582,27 +1584,25 @@ subroutine fv_phys_init(is, ie, js, je, km, nwat, ts, pt, time, axes, lat)
     master = is_master()
 
 !   ----- read and write namelist -----
-    if ( file_exist('input.nml')) then
-         unit = open_namelist_file ('input.nml')
-         read  (unit, nml=sim_phys_nml, iostat=io, end=10)
+    if ( file_exists('input.nml')) then
```
Comment (bensonr) [inline driver/solo/fv_phys.F90:1587]: Do we need this if-test since we'll be reading from the character variable?  That should've been checked during fms_init (mpp_init) at program startup.

File: driver/solo/ocean_rough.F90 [hunk 2]
```diff
@@ -100,15 +101,10 @@ subroutine compute_ocean_roughness (u_star, speed,     &
...
-    if ( read_namelist .and. file_exist('input.nml')) then
-          unit = open_namelist_file ('input.nml')
-          if(master) write(*,*)'read input, unit', unit
-           ierr=1; do while (ierr /= 0)
-           read  (unit, nml=ocean_rough_nml, iostat=io, end=10)
-           ierr = check_nml_error(io,'ocean_rough_nml')
-           if(master) write(*,*)'ierr =',ierr
-        enddo
- 10     call close_file (unit)
+    if ( read_namelist .and. file_exists('input.nml')) then
```
Comment (bensonr) [inline driver/solo/ocean_rough.F90:104]: I don't think we need the _.and. file_exists(...)_ portion of this if-test.

File: driver/solo/fv_phys.F90 (hunk 1 above)
Comment (laurenchilutti) [reply driver/solo/fv_phys.F90:1587]: `read_input_nml` checks if input.nml exists and `read_input_nml` is called within `mpp_init`, so it looks like you are right.  @uramirez8707 let me know if you see any reason we should keep this.

**Comment by laurenchilutti** [comment]
I have just pushed a commit that should resolve @bensonr comments.  If this is acceptable I will merge this PR into the dev/gfdl branch and cherry-pick this last commit to the main branch, as the [deprecated io PR to main](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/257) has already been merged.

**Review by uramirez8707 — APPROVED** [review]
