### PR TITLE
initialize two arrays and fix fortran coding error plus PRs #285 and #276

### LINKED ISSUE #279: String length mismatch violates fortran standard; UFS gnu debug builds abort
**Describe the bug**

This is not legal fortran:

```f90
    attrList=(/trim(axis_name),trim(axis_name)//":cartesian_axis"/)
```

All strings in the array must have the same length. They don't. Intel's compiler allows it as a language extension. GNU's compiler aborts at runtime when certain runtime checks are enabled. The ufs-weather-model regression tests fail this way, if the code reaches that line.

UFS's regression tests have a gnu debug build which catches errors like this.

**To Reproduce**
There is a ufs-regression-test called "conus13km_debug_qr" in this branch. When run with the gnu compiler, it aborts if it reaches that line. (Another unknown bug may cause it to abort earlier, which is why the gnu version of the test is presently disabled.)

**Expected behavior**
Code shouldn't require unnecessary language extensions.

**System Environment**
Describe the system environment, include:
- OS: CENTOS or RHEL (Hera and Cheyenne)
- Compiler(s): gnu compiler; Hera: 9.2.0, Cheyenne: 10.1.0
- MPI type, and version Hera: OpenMPI 4.1.5; Cheyenne: MPT 2.25
- netCDF Version: N/A
- Configure options: These are the debug options enabled for the GNU compiler: `-O0 -fno-unsafe-math-optimizations -frounding-math -fsignaling-nans -ffpe-trap=invalid,zero,overflow -fbounds-check`

**Additional context**
The new regression test that detects this is in:

https://github.com/ufs-community/ufs-weather-model/pull/1893

You must disable this bug fix and enable the conus13km_debug_qr test for the gnu compiler.

### LINKED ISSUE #281: two arrays are not initialized in fv_ufs_restart_io.F90
**Describe the bug**
Found by @DusanJovic-NOAA and detailed in https://github.com/ufs-community/ufs-weather-model/issues/1882#issuecomment-1712530336

The srf_wnd_var2 and tracers_var3 arrays are not initialized after allocation in fv_ufs_restart_io.F90. This can cause the ufs-weather-model write component's quilting restart to fail. When ESMF copies data from compute ranks to write ranks, it'll encounter NaN values if the uninitialized array happen to contain any.

**To Reproduce**
Read the code?

**Expected behavior**
Arrays should be initialized.

**System Environment**
Describe the system environment, include: N/A
Error is apparent in the code.

**Additional context**
Full details are here:

https://github.com/ufs-community/ufs-weather-model/issues/1882#issuecomment-1712530336

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
### Description

- Closes #285, which is included in this PR
- Closes #276, which is included in this PR
- Fixes #279 
- Fixes #281

#### #279: fortran coding error: string length mismatch

Wherein a string length mismatch causes an abort. The code does not follow the fortran standard on this line:

```f90
    attrList=(/trim(axis_name),trim(axis_name)//":cartesian_axis"/)
```

because the two strings in the array have different lengths. See #279 for details.

#### #281: uninitialized arrays

The srf_wnd_var2 and tracers_var3 arrays are not initialized after allocation in fv_ufs_restart_io.F90. This can cause the ufs-weather-model write component's quilting restart to fail. When ESMF copies data from compute ranks to write ranks, it'll encounter NaN values if the uninitialized array happen to contain any.

### How Has This Been Tested?

ufs-weather-model regression tests.

Specifically, the gnu version of the `conus13km_qr_debug` regression test.

The regression test can be found in this branch. To see the failure, disable this bug fix.

https://github.com/ufs-community/ufs-weather-model/pull/1893

### Checklist:

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: driver/fvGFS/fv_ufs_restart_io.F90 [hunk 1]
```diff
@@ -132,6 +132,7 @@ subroutine fv_dyn_restart_register (Atm)
    ! srf_wnd
    nvar2d_srf_wnd = 2
    allocate (srf_wnd_var2(nx,ny,nvar2d_srf_wnd), srf_wnd_var2_names(nvar2d_srf_wnd))
```
Comment (lharris4) [inline driver/fvGFS/fv_ufs_restart_io.F90:134]: Do any of the UFS applications use fv_srf_wind.res? This is used for AM4 (I believe) but not in SHiELD.

File: driver/fvGFS/fv_ufs_restart_io.F90 [hunk 2]
```diff
@@ -141,6 +142,7 @@ subroutine fv_dyn_restart_register (Atm)
    nvar3d_tracers = ntprog+ntdiag
    tracers_zsize = size(Atm%q,3)
    allocate (tracers_var3(nx,ny,tracers_zsize,nvar3d_tracers), tracers_var3_names(nvar3d_tracers))
+   tracers_var3 = 0.0
```
Comment (lharris4) [inline driver/fvGFS/fv_ufs_restart_io.F90:145]: Best practice in multi-threaded simulations is to loop over elements to ensure each cell is allocated on the correct thread, although modern compilers might get around this.

File: driver/fvGFS/fv_ufs_restart_io.F90 (hunk 1 above)
Comment (SamuelTrahanNOAA) [reply driver/fvGFS/fv_ufs_restart_io.F90:134]: All UFS applications use it, if they enable quilting restart. From atmos_model.F90 subroutine atmos_model_init:

```f90
   if (quilting_restart) then
      call fv_dyn_restart_register (Atm(mygrid))
      call fv3atm_restart_register (GFS_data%Sfcprop, GFS_restart_var, Atm_block, GFS_control)
   endif
```

File: driver/fvGFS/fv_ufs_restart_io.F90 (hunk 2 above)
Comment (SamuelTrahanNOAA) [reply driver/fvGFS/fv_ufs_restart_io.F90:145]: Normally you would be right, but not here. The correct thread is the master thread.

The rest of fv_ufs_restart_io.F90 does not use OpenMP directives. Hence, tracers_var3 is only ever used by the master thread. Using OpenMP to initialize tracers_var3 would distribute it across multiple CPUs. If some threads are in different NUMA nodes than the master thread, then this will slow down the program.

Adding OpenMP directives throughout fv_ufs_restart_io.F90 is outside the scope of this PR. Also, there may be good reasons why the restart code is single-threaded. I can't think of any, but somebody probably implemented it this way for a reason.

File: driver/fvGFS/fv_ufs_restart_io.F90 (hunk 1 above)
Comment (SamuelTrahanNOAA) [reply driver/fvGFS/fv_ufs_restart_io.F90:134]: I will ping @DusanJovic-NOAA for comment on this.

Comment (DusanJovic-NOAA) [reply driver/fvGFS/fv_ufs_restart_io.F90:134]: The fv_srf_wnd.res restart file is always written:

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/dev/emc/tools/fv_io.F90#L847-L858

regardless on which UFS configuration is used.

However in read routine:

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/dev/emc/tools/fv_io.F90#L486-L498

I see that if the file is not present in the run directory it will print warning and continue execution. Whether this file is needed to get b4b identical restart run compared to non-restart I'm not sure, I guess we can run test to see what will happen if we do not create this file. If the restart is b4b,  maybe we can skip writing/reading this file in UFS.

Comment (SamuelTrahanNOAA) [reply driver/fvGFS/fv_ufs_restart_io.F90:134]: Regardless of whether the file is written, you should initialized your arrays.

Comment (DusanJovic-NOAA) [reply driver/fvGFS/fv_ufs_restart_io.F90:134]: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/dev/emc/tools/fv_io.F90#L692-L693

Is `else` missing between line 692 and 693?

Comment (DusanJovic-NOAA) [reply driver/fvGFS/fv_ufs_restart_io.F90:134]: I should mention that this is relevant to this PR I just noticed this while looking at where and how fv_srf_wnd.res is created and used.

Comment (bensonr) [reply driver/fvGFS/fv_ufs_restart_io.F90:134]: @DusanJovic-NOAA - It looks like it might be missing.  Please open an issue detailing your concern with this section of tools/fv_io.F90

**Comment by zach1221** [comment]
Hello, @lharris4 @bensonr are you able to continue reviewing this PR?

**Review by lharris4 — APPROVED** [review]

**Comment by lharris4** [comment]
Hi, Zach. I hadn't realized I was a reviewer. I have approved the PR and it
should be able to move forward soon.

Thanks
Lucas

**Comment by lharris4** [comment]
BTW @bensonr is on leave today ; he should be back on Monday.

**Comment by SamuelTrahanNOAA** [comment]
I've merged #283 into this PR since that one is expected to go in first. This is just to speed up the UFS test process.

In the unlikely event that #283 is rejected, I'll back out those changes.

**Comment by lharris4** [comment]
Thanks for taking the lead on this. These changes should be fine.

Lucas

**Review by bensonr — APPROVED** [review]

**Comment by bensonr** [comment]
> I've merged #283 into this PR since that one is expected to go in first. This is just to speed up the UFS test process.
> 
> In the unlikely event that #283 is rejected, I'll back out those changes.
> 
> EDIT: The testing of #283, at the ufs-weather-model level, as [ufs-community/ufs-weather-model#1903](https://github.com/ufs-community/ufs-weather-model/pull/1903), is almost done.

As you've included this here, should we have @DusanJovic-NOAA close the #283?

**Comment by SamuelTrahanNOAA** [comment]
> As you've included this here, should we have @DusanJovic-NOAA close the https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/283?

No. That PR should be merged now.

**Comment by laurenchilutti** [comment]
@SamuelTrahanNOAA I have just merged PR 283 into the dev/emc branch, but this PR is still showing the changes from PR 283 in the list of changes.  Could you please merge in dev/emc branch to this branch? I believe that GitHub is confusing your merge of Dusan's changes in commit 81f254d95aba6fb9ae94a18b432eb1a4be3799a8 with the actual PR 283 dev/emc merge commit.

**Comment by SamuelTrahanNOAA** [comment]
> Could you please merge in dev/emc branch to this branch?

I have merged dev/emc to this branch. Please wait to merge my PR until the UFS code managers finish testing it at the ufs-weather-model level.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by bensonr — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
Could @junwang-noaa and @laurenchilutti please confirm that your PRs were merged into this one correctly?

**Review by bensonr — APPROVED** [review]

**Review by laurenchilutti — APPROVED** [review]

**Comment by jkbk2004** [comment]
@laurenchilutti As @SamuelTrahanNOAA 's mini-test went ok through https://github.com/ufs-community/ufs-weather-model/pull/1893, I don't see any major issue to merge this pr. Can you go ahead to merge in this pr by the end of today?
