### PR TITLE
FMS2_IO: correcting restart reads in remap_restarts

### LINKED ISSUE #204: Vertical remapping on restart distorts phis field
**Describe the bug**
When we restart a simulation with a different vertical grid, the phis field becomes distorted, copying the same section of the field over the whole tile according to the number of processors per tile (picture attached).
Screen Shot 2022-07-19 at 2 03 45 PM
 
This happens when both going up or down in vertical resolution. Normal restarts do not experience this problem. This was confirmed to behave the same in the main branch, commit [29396d3], and FMS tag 2022.02

**To Reproduce**
Warm start a simulation with a different NPZ.

**Expected behavior**
We expect the phis field to be initialized correctly, copying what was in the fv_core.tileX.nc file.

**System Environment**
Describe the system environment, include:
- OS:   Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.9:GA:server
            Kernel: Linux 3.10.0-1160.66.1.1chaos.ch6.x86_64
      Architecture: x86-64
- Compiler(s): ifort version 19.1.3.304
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI): mpi-hpe/mpt.2.25
- netCDF Version: 4.4.1.1
- Configure options: -DSPMD -Duse_libMPI -Duse_netCDF -DINTERNAL_FILE_NML -DCUBE_CORE -fpp -Wp,-w -fno-alias -ftz -assume byterecl -i4 -r8 -nowarn -O2 -fp-model precise -qoverride-limits -c -qopenmp -traceback -xSSE4.2

**Additional context**
It seems like an issue in the read_data call for phis in remap_restart in fv_io.F90. When we moved the phis field to fv_srf_wnd.res which uses read_restart instead, we did not see this problem.

### PR DESCRIPTION
**Pull request by laurenchilutti**
**Description**

The reading of restarts in the fv_io.F90 `remap_restarts` subroutine was mistakenly using read_data (fms2_io) rather than read_restart (fms2_io).  This led to the issues seen in issue #204.  This PR corrects this issue.

Fixes #204 

**How Has This Been Tested?**

Tested on Gaea with regression tests

**Checklist:**

Please check all whether they apply or not
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: tools/fv_restart.F90 [hunk 1]
```diff
@@ -253,10 +253,6 @@ subroutine fv_restart(fv_domain, Atm, dt_atmos, seconds, days, cold_start, grid_
        !This call still appears to be necessary to get isd, etc. correct
        !call switch_current_Atm(Atm(n)) !TODO should NOT be necessary now that we manually set isd, etc.
 
-       !--- call fv_io_register_restart to register restart field to be written out in fv_io_write_restart
```
Comment (lharris4) [inline tools/fv_restart.F90:256]: Much appreciated clean-up.

**Review by lharris4 — APPROVED** [review]

File: tools/fv_io.F90 [hunk 2]
```diff
@@ -709,22 +743,25 @@ subroutine  remap_restart(Atm)
...
           if (Atm(1)%flagstruct%is_ideal_case) then
-             call read_data(Fv_tile_restart_r, 'u0', u0_r)
-             call read_data(Fv_tile_restart_r, 'v0', v0_r)
+             call register_restart_field (Fv_tile_restart_r, 'u0', u0_r, dim_names_4d_u, is_optional=.true.)
+             call register_restart_field (Fv_tile_restart_r, 'v0', v0_r, dim_names_4d_v, is_optional=.true.)
           endif
-          call read_data(Fv_tile_restart_r, 'u', u_r)
-          call read_data(Fv_tile_restart_r, 'v', v_r)
+          call register_restart_field (Fv_tile_restart_r, 'u', u_r, dim_names_4d_u, is_optional=.true.)
+          call register_restart_field (Fv_tile_restart_r, 'v', v_r, dim_names_4d_v, is_optional=.true.)
```
Comment (bensonr) [inline tools/fv_io.F90:753]: These should not be optional existience variables.  Please look at the original mpp_io version to confirm.

**Review by bensonr — COMMENTED** [review]
Minor question regarding existence flag for variables.

**Review by bensonr — APPROVED** [review]
lgtm.  Is there a test case for this?

**Comment by laurenchilutti** [comment]
@bensonr no I do not have a test case for this
